spring:
  application:
    name: paste-test
  datasource:
    url: "jdbc:sqlite::memory:"
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  base-url: "http://localhost:8080"
